"use server"

import { redirect } from "next/navigation"
import { createClient } from "@/lib/supabase/server"
import { createAdminClient } from "@/lib/supabase/admin"
import { memberIdToEmail, getCurrentRole } from "@/lib/auth/helpers"

export type SignupState = { error: string } | { memberId: number } | null
export type LoginState = { error: string } | null

/**
 * Creates a new member: one row in `members`, one linked Supabase Auth
 * account. Uses the admin client because Supabase Auth's regular signUp
 * would try to send a confirmation email to our fake internal address.
 * The admin client creates the account pre-confirmed instead.
 *
 * Returns the newly assigned Member ID to show the person — it's their
 * login ID going forward, generated by the database, not chosen by them.
 */
export async function signupMember(
  _prevState: SignupState,
  formData: FormData
): Promise<SignupState> {
  const name = String(formData.get("name") ?? "").trim()
  const password = String(formData.get("password") ?? "")
  const tierId = Number(formData.get("tier_id"))
  const locationId = Number(formData.get("location_id"))

  if (!name || !password || !tierId || !locationId) {
    return { error: "All fields are required." }
  }
  if (password.length < 6) {
    return { error: "Password must be at least 6 characters." }
  }

  const admin = createAdminClient()

  // 1. Create the member row first so we get a database-assigned member_id.
  const { data: memberRow, error: insertError } = await admin
    .from("members")
    .insert({ name, tier_id: tierId, location_id: locationId })
    .select("member_id")
    .single()

  if (insertError || !memberRow) {
    return { error: insertError?.message ?? "Could not create member record." }
  }

  const memberId = memberRow.member_id

  // 2. Create the linked auth account, pre-confirmed, using the
  // Member ID to build the internal email.
  const { data: authData, error: authError } = await admin.auth.admin.createUser({
    email: memberIdToEmail(memberId),
    password,
    email_confirm: true,
    user_metadata: { role: "member", member_id: memberId },
  })

  if (authError || !authData.user) {
    // Roll back the member row so we don't leave an orphaned record.
    await admin.from("members").delete().eq("member_id", memberId)
    return { error: authError?.message ?? "Could not create login." }
  }

  // 3. Link the two records together.
  const { error: linkError } = await admin
    .from("members")
    .update({ auth_user_id: authData.user.id })
    .eq("member_id", memberId)

  if (linkError) {
    return { error: linkError.message }
  }

  return { memberId }
}

/**
 * Member login: translates the Member ID into its internal email,
 * signs in normally through the regular (non-admin) client, then
 * redirects to the member portal.
 */
export async function loginMember(
  _prevState: LoginState,
  formData: FormData
): Promise<LoginState> {
  const memberId = String(formData.get("member_id") ?? "").trim()
  const password = String(formData.get("password") ?? "")

  if (!memberId || !password) {
    return { error: "Member ID and password are required." }
  }

  const supabase = await createClient()
  const { error } = await supabase.auth.signInWithPassword({
    email: memberIdToEmail(memberId),
    password,
  })

  if (error) {
    return { error: "Invalid Member ID or password." }
  }

  redirect("/portal")
}

/**
 * Employee login: employees already have a real email column in the
 * schema, so this is a direct, ordinary email + password sign-in.
 */
export async function loginEmployee(
  _prevState: LoginState,
  formData: FormData
): Promise<LoginState> {
  const email = String(formData.get("email") ?? "").trim()
  const password = String(formData.get("password") ?? "")

  if (!email || !password) {
    return { error: "Email and password are required." }
  }

  const supabase = await createClient()
  const { error } = await supabase.auth.signInWithPassword({ email, password })

  if (error) {
    return { error: "Invalid email or password." }
  }

  redirect("/admin")
}

export async function logout() {
  const supabase = await createClient()
  await supabase.auth.signOut()
  redirect("/login")
}

/**
 * Convenience export for pages/middleware that just need to know
 * "who is this and what portal do they belong in."
 */
export async function currentRole() {
  const supabase = await createClient()
  return getCurrentRole(supabase)
}
